# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Windows Build for hasaki

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]
env:
  QT_VERSION: '6.6.3'
  QT_HOST: windows
  BUILD_TYPE: Release

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/Qt 
        key: ${{ runner.os }}-qt-${{ env.QT_VERSION }}-${{ 'win64_msvc2019_64' }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        arch: win64_msvc2019_64
        # 关键点: 告诉 action 缓存是否命中
        # 如果上一步 'cache-qt' 命中缓存，这里的值为 'true'
        # action 在接收到 cached: 'true' 时，会跳过下载和安装，只设置环境变量
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        
    - name: Configure CMake
      shell: bash
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel
      
    - name: Deploy Qt Dependencies
      run: windeployqt --release build/${{env.BUILD_TYPE}}/hasaki.exe

    - name: Archive release files
      shell: pwsh
      run: |
        $assetName = "hasaki-${{ github.ref_name }}-windows.zip"
        $assetPath = "build/${{env.BUILD_TYPE}}"
        7z a $assetName $assetPath/*
        echo "ASSET_NAME=$assetName" >> $env:GITHUB_ENV

    - name: Create GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        body: ${{ github.event.release.body }}
        files: ${{ env.ASSET_NAME }}
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hasaki-windows-build-raw
        path: build/${{env.BUILD_TYPE}}/
